name: dotnet package

on: [push]

env:
  dotnetVersion: "7.0.19"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet $dotnetVersion
        uses: actions/setup-dotnet@v3

      - name: Display dotnet version
        run: dotnet --version

      - name: Install dependencies
        run: dotnet build WebAPI/WebAPI.Services.Tests/WebAPI.Services.Tests.csproj

      - name: Execute tests
        run: dotnet test WebAPI/WebAPI.Services.Tests/WebAPI.Services.Tests.csproj
